# Generated by Django 2.0.8 on 2018-09-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0018_segment_excluded_users'),
        ('wagtail_personalisation', '0013_auto_20180605_1712'),
    ]

    operations = [
    ]
